### ISSUE TITLE
Motif Search in time series

### ISSUE THREAD

**Issue by raul-rufato** [debiai/DebiAI#95]
I would like a solution that takes an specific motif from the time series, and look at the entire time series measuring the distance between the time series and the motif to be able to recognize this motif in other parts of the series. 
An alternative is to measure the Euclidian distance between the motif and the time series.

**Comment by Tomansion** [comment]
Hi @raul-rufato , thank you again for your suggestion.
Unfortunately, motif detection won't be implemented in the next few months because we have other priorities.

However, we are working on a feature where you will be able to link any Python algorithm with data from the DebiAI dashboard. This feature will be perfect for you, but it won't be available before June 2023. 

It is however possible to implement a semi-real-time motif analysis with the current DebiAI capacities, this is how I would have done it:

1. If you are using a project created with our Python module, switch to a data-provider project.
This is takes more time to setup, but will be beneficial at the long run, more info here : [DebiAI dataProviders](https://debiai.irt-systemx.fr/dataInsertion/dataProviders/)

2. Add a new HTTP route in your data-provider that takes a 1D time series data range that look for the motif, then add/modify a new column with a float/integer corresponding to the Euclidean distance between the motif and the time series.

3. Set this route as an export method to DebiAI, you will then be able to find motif from DebiAI, reloading the project will provide the calculated data. 
More info on data export from DebiAI here : [DebiAI data-export](https://debiai.irt-systemx.fr/dashboard/dataExport/)

If you plan to follow this, don't mind asking for help!

**Comment by Tomansion** [comment]
Just to let you know @raul-rufato , it is now possible to add custom algorithms to DebiAI with our new [algo-providers](https://debiai.irt-systemx.fr/dashboard/algoProviders/) feature.

This is still a new feature, let us know if you need assistance.
